# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shakestat
email: allison@allizad.com
description: >
  The fastest and easiest way to search through Shakespeare's work and
  explore its language statistics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: allizad
github_username:  allizad
permalink: /:title.html
destination: public

# elasticsearch:
#   url: ""
#   index_name: "jekyll-shakestat"


# Build settings
markdown: kramdown

exclude:
  - node_modules

gems:
  - kramdown
  - jekyll
  # - github-pages
  # - searchyll
